### PR TITLE
Added MU calculation and removed hubot command to set TZ in chat

### PR DESCRIPTION
**Pull request by impleri**

### CODE REVIEW

**Comment by therealklanni** [comment]
What's the reasoning behind removing the TZ commands? I'm not sure how many people are making use of this and removing it could impact current users. Though maybe there's something I'm missing?

**Comment by impleri** [comment]
Whoops. Bad merging.

**Comment by impleri** [comment]
Fixed. The working copy I copied the files from had them removed from some strange night long ago.

**Comment by therealklanni** [comment]
Published 0.15.0. Sorry about the delay, got sidetracked with other stuff.

**Pull request merged**
