### PR TITLE
Add listeners to calculate checkpoint times for a specific day/date

### PR DESCRIPTION
**Pull request by impleri**
As the title says. Allows `hubot cps on Sunday` to get all checkpoints on the upcoming Sunday.

### CODE REVIEW

**Comment by therealklanni** [comment]
Looks good. And thanks for adding tests for the listeners. Could you also add a test for each listener that covers an example user interaction with the new functionality?

**Comment by impleri** [comment]
Sure can. Won't be until the weekend, though.

**Comment by impleri** [comment]
Finally updated.

**Comment by therealklanni** [comment]
Published 0.16.0

**Pull request merged**
