### PR TITLE
Add Translator and Recruiter badges

### PR DESCRIPTION
**Pull request by AgentNormandy**
In reference to https://github.com/hubot-scripts/hubot-ingress/issues/23, I went ahead and added the recruiter badges as well.

### CODE REVIEW

**Comment by therealklanni** [comment]
Great, thanks so much for your help with these! Will get it merged tonight.

**Comment by s4nf4n** [comment]
May I ask what happened to the merge?

**Comment by therealklanni** [comment]
I was sick, so it must have slipped my mind. :)

**Comment by therealklanni** [comment]
v0.10.0 published

**Pull request merged**
