### PR TITLE
Add commands for list badges and display badges

### PR DESCRIPTION
**Pull request by AgentNormandy**
Per: https://github.com/hubot-scripts/hubot-ingress/issues/14

### CODE REVIEW

**Comment by therealklanni** [comment]
Thanks, I'll run this locally on my hubot and try to get some feedback this weekend. Have you gotten any feedback on your instance?

**Comment by AgentNormandy** [comment]
Haven't really gotten much feedback but we are a pretty small community and hubot is pretty new so not being widely used yet. 

Main thing I wasn't sure about was the formatting of the badge names, if people prefer it formatted as code or if regular text would be better. Its an easy change if so.

**Comment by therealklanni** [comment]
I think we should remove the ` from this. We shouldn't assume they are using Slack with this plugin and it might look ugly in plain text.

**Comment by AgentNormandy** [comment]
Ok, I've removed the ` from the output.

**Comment by therealklanni** [comment]
Please branch your changes so this PR doesn't include the changes specific to #21 (your commit 3eed6ff). This ensures we have a clean history of changes. :) thanks.

**Comment by therealklanni** [comment]
Looks good, thanks. I'll merge this in and publish a new version when I get a chance.

**Comment by therealklanni** [comment]
Published 0.8.0

**Pull request merged**
