### PR TITLE
Add support for adding badges by color

### LINKED ISSUE #15: Allow badge color/rank to be specified by name
When someone says "I have the black guardian badge" add the guardian5 badge, for example. Bonus: if someone says "I have the guardian badge" add the lowest rank (guardian1).

### PR DESCRIPTION
**Pull request by impleri**
Fixes #15.

### CODE REVIEW

**Comment by therealklanni** [comment]
@impleri so is this a work in progress or is it ready to be merged? Let's put `[wip]` on the title of any PRs that shouldn't be merged yet.

**Comment by impleri** [comment]
Sorry. This is now ready to merge. I thought it was complete last night until I thought through the use case of adding a tiered badge without a color (i.e. "I have the guardian badge") vs a single-tier badge (i.e. "I have the shonin badge"). Last commit added another test for that and adjustments.

**Comment by therealklanni** [comment]
Looks great, thanks!

**Comment by therealklanni** [comment]
Published v0.12.0

**Pull request merged**
