### PR TITLE
Add Shonin and Illuminator Badges

### PR DESCRIPTION
**Pull request by AgentNormandy**
Added the images for the Shonin and Illuminator Badges and updated the badge lists in badges.coffee. Attaching example of output. 
capture

### CODE REVIEW

**Comment by mack-hankins** [comment]
:+1:

**Comment by AgentNormandy** [comment]
Of course now they release Sojourner badge. Guess I'll add that to this as well as soon as I can.

**Comment by therealklanni** [comment]
Sorry about the delay. As soon as you update this branch with the newest stuff I'll get it merged.

**Comment by mack-hankins** [comment]
@AgentNormandy the new badge images are out btw.  http://niantic.schlarp.com/investigation:apps:ingress:badges

**Comment by AgentNormandy** [comment]
@mack-hankins I know just haven't had the time till today. @therealklanni should be set now. Unless they plan to release another badge this week...

**Comment by therealklanni** [comment]
Published hubot-ingress@0.11.0

**Pull request merged**
